name: digital_picture_frame_starter
description: A Digital Picture Frame (Lab 3)
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Smooth animated transitions & general material icons
  cupertino_icons: ^1.0.6

  # Optional: Cached image loading for faster slideshow performance
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
